settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: thehomesihavemade-com
    name: thehomesihavemade.com
    url: 'https://thehomesihavemade.com/'
    method: GET
    expectStatus: 200
    
  - id: www-wholekitchensink-com
    name: www.wholekitchensink.com
    url: 'https://www.wholekitchensink.com'
    method: GET
    expectStatus: 200
    
  - id: Momcrieff-com
    name: momcrieff.com
    url: 'https://momcrieff.com'
    method: GET
    expectStatus: 200
