settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: thehomesihavemade-com
    name: thehomesihavemade.com
    url: 'https://thehomesihavemade.com/'
    method: GET
    expectStatus: 200
    
  - id: www-wholekitchensink-com
    name: www.wholekitchensink.com
    url: 'https://www.wholekitchensink.com'
    method: GET
    expectStatus: 200
    
  - id: Momcrieff-com
    name: momcrieff.com
    url: 'https://momcrieff.com'
    method: GET
    expectStatus: 200
    
  - id: petiteinparis-com
    name: petiteinparis.com
    url: 'https://petiteinparis.com'
    method: GET
    expectStatus: 200
    
  - id: mypureplants-com
    name: mypureplants.com
    url: 'https://mypureplants.com'
    method: GET
    expectStatus: 200
    
  - id: planetnatural-com
    name: www.planetnatural.com
    url: 'https://www.planetnatural.com'
    method: GET
    expectStatus: 200
    
  - id: thegadgetbuyer-com
    name: thegadgetbuyer.com
    url: 'https://thegadgetbuyer.com'
    method: GET
    expectStatus: 200
   
  - id: wellkeptwallet-com
    name: wellkeptwallet.com
    url: 'https://wellkeptwallet.com'
    method: GET
    expectStatus: 200
    
  - id: nerdsandscoundrels-com
    name: www.nerdsandscoundrels.com
    url: 'https://www.nerdsandscoundrels.com'
    method: GET
    expectStatus: 200
    
  - id: parkedinparadise-com
    name: www.parkedinparadise.com
    url: 'https://www.parkedinparadise.com'
    method: GET
    expectStatus: 200
